play.http.secret.key = "changeme"
play.http.secret.key = ${?APPLICATION_SECRET}

couchdb.url      = ${COUCHDB_URL}
couchdb.database = ${COUCHDB_DATABASE}
couchdb.username = ${COUCHDB_USERNAME}
couchdb.password = ${COUCHDB_PASSWORD}
