play.http.secret.key = "changeme"
play.http.secret.key = ${?APPLICATION_SECRET}

couchdb.url      = "http://localhost:5984"
couchdb.url      = ${?COUCHDB_URL}
couchdb.database = "scavengerhunt"
couchdb.database = ${?COUCHDB_DATABASE}
